services:
  - type: web
    name: heka-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heka-db
      - key: JWT_SECRET
        value: heka_secret_2024
